# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(344, 166)
        self.groupBox = QtWidgets.QGroupBox(Login)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 151))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 291, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_login = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_login.setMinimumSize(QtCore.QSize(54, 0))
        self.label_login.setObjectName("label_login")
        self.horizontalLayout.addWidget(self.label_login)
        self.lineEdit_login = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.horizontalLayout.addWidget(self.lineEdit_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_pass = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_pass.setMinimumSize(QtCore.QSize(54, 0))
        self.label_pass.setObjectName("label_pass")
        self.horizontalLayout_2.addWidget(self.label_pass)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.horizontalLayout_2.addWidget(self.lineEdit_pass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_login = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_login.setObjectName("pushButton_login")
        self.horizontalLayout_3.addWidget(self.pushButton_login)
        self.pushButton_back = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_back.setObjectName("pushButton_back")
        self.horizontalLayout_3.addWidget(self.pushButton_back)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Авторизация"))
        self.groupBox.setTitle(_translate("Login", "Вход в систему"))
        self.label_login.setText(_translate("Login", "Логин"))
        self.label_pass.setText(_translate("Login", "Пароль"))
        self.pushButton_login.setText(_translate("Login", "Вход"))
        self.pushButton_back.setText(_translate("Login", "Назад"))
