# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(410, 254)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 210, 391, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_registration = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_registration.setObjectName("pushButton_registration")
        self.horizontalLayout.addWidget(self.pushButton_registration)
        self.pushButton_schedule = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_schedule.setObjectName("pushButton_schedule")
        self.horizontalLayout.addWidget(self.pushButton_schedule)
        self.pushButton_autorization = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_autorization.setObjectName("pushButton_autorization")
        self.horizontalLayout.addWidget(self.pushButton_autorization)
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(20, 10, 381, 201))
        self.image.setObjectName("image")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ИС Поликлиника"))
        self.pushButton_registration.setText(_translate("mainWindow", "Регистрация"))
        self.pushButton_schedule.setText(_translate("mainWindow", "Расписание"))
        self.pushButton_autorization.setText(_translate("mainWindow", "Авторизация"))
        self.image.setText(_translate("mainWindow", "TextLabel"))
